"""Writes src/holdem_preflop_table.inc, the heads-up Hold'em preflop table.

Every row comes from the extension's own enumeration counters, so the table
holds exactly the counters a call without it would build. Both paths turn the
counters into doubles with the same function, so the results are the same.

The extension the script imports must be built first, and it must be built
with a table, because `src/holdem_preflop.h` asserts the row count. The table
never changes, so a rebuild only follows a change to the key encoding:

    pip install -e .
    python tools/generate_holdem_preflop_table.py
    pip install -e .

The enumeration releases the GIL, so the threads run in parallel.
"""

import itertools
import os
import pathlib
from concurrent.futures import ThreadPoolExecutor

from eqcalc import _core

#: C(48, 5): the boards two hands leave.
BOARD_COUNT = 1_712_304
#: The enumeration weights each runout by factorial(2).
FACT = 2
ROWS_PER_LINE = 3
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "holdem_preflop_table.inc"

RANKS = "23456789TJQKA"
SUITS = "cdhs"


def card_string(card: int) -> str:
    return RANKS[card // 4] + SUITS[card % 4]


def representatives() -> dict[int, tuple[list[int], list[int]]]:
    """One matchup per key, in the order the table stores it."""
    hands = list(itertools.combinations(range(52), 2))
    found: dict[int, tuple[list[int], list[int]]] = {}
    for first, second in itertools.combinations(hands, 2):
        if set(first) & set(second):
            continue
        key, swapped = _core._holdem_preflop_key(list(first), list(second))
        if key not in found:
            found[key] = (list(second), list(first)) if swapped else (list(first), list(second))
    return found


def row_of(key: int, first: list[int], second: list[int]) -> tuple[int, int, int]:
    hands = ["".join(map(card_string, first)), "".join(map(card_string, second))]
    counts = _core._count_runouts_from_string(hands=hands)
    if counts.total != FACT * BOARD_COUNT or any(win % FACT for win in counts.win):
        raise RuntimeError(f"{hands}: the counters do not fit the table layout")
    return key, counts.win[0] // FACT, counts.win[1] // FACT


def main() -> None:
    matchups = representatives()
    print(f"{len(matchups)} matchups")

    with ThreadPoolExecutor(max_workers=os.cpu_count()) as pool:
        rows = sorted(pool.map(lambda item: row_of(item[0], *item[1]), matchups.items()))

    lines = [
        "// Generated by tools/generate_holdem_preflop_table.py. Do not edit.",
        "// {key, first_wins, second_wins}",
        "// clang-format off",
    ]
    cells = [f"{{0x{key:06x}, {first}, {second}}}," for key, first, second in rows]
    for start in range(0, len(cells), ROWS_PER_LINE):
        lines.append(" ".join(cells[start : start + ROWS_PER_LINE]))
    lines.append("// clang-format on")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
